# Numpy의 기본 사용법 
나동빈 유튜브를 통해 학습 
https://www.youtube.com/watch?v=LdoJAC26MIc&list=PLRx0vPvlEmdBx9X5xSgcEk4CEbzEiws8C&index=4

numpy는 다차원 배열을 효과적으로 처리할 수 있도록 도와주는 도구  
python의 기본 list에 비해 빠르고 강력한 기능을 제공  
  
1차원 축 axis 0 -> 벡터  
2차원 축 axis 1 -> 매트릭스  
3차원 축 axis 2 -> 텐서(3차원이상)

In [3]:

# list를 numypy로 변경하기

import numpy as np

list_data = [1,2,3]
array = np.array(list_data)

print(array)
print(array.size)
print(array.dtype)
print(array[2])

[1 2 3]
3
int64
3


In [10]:
# numpy 배열 초기화

# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
print(array1)

array2 = np.zeros((4,4), dtype=float)
print(array2)

array3 = np.ones((3,3), dtype=str)
print(array3)

# 0부터 9까지 랜덤하기 초기화된 배열 만들기
array4 = np.random.randint(0,10, (3,3))
print(array4)

# 평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3,3))
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[0 8 1]
 [3 5 5]
 [3 2 5]]
[[ 1.00338498  0.23046191 -0.55589934]
 [ 1.2623395   0.63080519 -0.88763401]
 [-1.18639694 -0.16416606  0.51994244]]


In [11]:
# numpy 배열 합치기

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [14]:
# numpy 배열 형태 바꾸기

array1 = np.array([1,2,3,4])
array2 = array1.reshape( [2,2])

print(array2)

[[1 2]
 [3 4]]


In [18]:
# numpy 배열 세로축으로 합치기

array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)

print(array1)
print(array2)

array3 = np.concatenate ([array1, array2], axis =0)

print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [21]:
# 배열 나누기

array = np.arange(8).reshape(2,4)
left , right = np.split(array, [2], axis=1)
print(array)
print('------------')

print(left)
print(left.shape)

print('------------')

print(right)
print(right.shape)


[[0 1 2 3]
 [4 5 6 7]]
------------
[[0 1]
 [4 5]]
(2, 2)
------------
[[2 3]
 [6 7]]
(2, 2)
