# Numpy의 기본 연산

- numpy는 배열에 대한 기본적인 사칙연산을 지원 

In [8]:
# numpy 상수 연산

import numpy as np 

arrayy = np.array(range(1,5))
print(arrayy)

array = np.random.randint(1,10, size=4).reshape(2,2)
print(array)
array = array *10
print(array)


[1 2 3 4]
[[4 9]
 [4 5]]
[[40 90]
 [40 50]]


In [ ]:
# 서로 다른 형태의 numpy 연산
# 서로 다른 형태의 배열을 연산할 때는 행 우선으로 수행됨 (broadcasting)

array1 = np.arange(4).reshape(2,2)
array2 = np.arange(2)

array3 = array1 + array2

print(array1)
print(array2)
print(array3)


[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]


In [12]:
# 브로드캐스트 : 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환 

array1 = np.arange(8).reshape(2,4)
array2 = np.arange(8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis=0)
array4 = np.arange(4).reshape(4,1)

print(array4)
print (array3)

print(array3+array4)

[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [ ]:
# numpy의 마스킹 연산 
# 마스킹 :각 원소에 대하여 체크
# 하나씩 체크보다 마스킹이 성능이 더 좋음 

array1 = np.arange(16).reshape(4,4)
print(array1)

array2 = array1<10

print(array2)

array1[array2] = 100

print(array1)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [ ]:
# numpy 집계 함수

array = np.arange(16).reshape(4,4)
print(array)

print("최대값" , np.max(array))
print("최소값" , np.min(array))
print("합계" , np.sum(array))
print("평균" , np.mean(array))




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
최대값 15
최소값 0
합계 120
평균 7.5


In [18]:
array = np.arange(16).reshape(4,4)
print(array)

print("각 열의 합계 " , np.sum(array,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
각 열의 합계  [24 28 32 36]
